import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Nav from "@/components/nav/nav";
import Footer from "@/components/footer/footer";
import { Poppins } from "next/font/google";
import ReduxProvider from "@/utils/redux/ReduxProvider";
import { Toaster } from "react-hot-toast";
import NextAuthProvider from "@/nextAuthProviderContext/provider";

const poppins = Poppins({
  weight: ["400", "400"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="dark">
      <ReduxProvider>
        <NextAuthProvider>
          <body className={`${poppins.className}`}>
            <Toaster
              toastOptions={{
                style: {
                  background: "rgb(0, 155, 255)",
                  color: "white",
                },
              }}
            />
            <Nav />
            {children}
            <Footer />
          </body>
        </NextAuthProvider>
      </ReduxProvider>
    </html>
  );
}
